apiVersion: srvcs.cloud/v1
kind: ProductionPromotion
metadata:
  name: www
spec:
  service: www
  environment: prod
  image: ghcr.io/srvcs/www:75be6776f6d09b1fdde2ec3b94eea24a94f752d7
  sourceCommit: 75be6776f6d09b1fdde2ec3b94eea24a94f752d7
  domains:
    - srvcs.cloud
    - www.srvcs.cloud
  runtime:
    cluster: prod
    namespace: srvcs-prod
    replicas: 1
  justification: srvcs.cloud requires a public website.
