apiVersion: v1
kind: ServiceAccount
metadata:
  name: srvcs-www
  namespace: srvcs-prod
  labels:
    app.kubernetes.io/name: srvcs-www
    app.kubernetes.io/part-of: srvcs
automountServiceAccountToken: false
